### PR TITLE
[#307] Add next button for the initiative form

### PR DESCRIPTION
**Pull request by punchagan**

### CODE REVIEW

**Comment by iperdomo** [comment]
@punchagan now the button is aligned. I wonder (from UX point of view) if the button should only be enabled if the user is *allowed* to move to the next page, meaning, has filled in all required fields. What about `Previous` button? 🤔

**Comment by punchagan** [comment]
> I wonder (from UX point of view) if the button should only be enabled if the user is allowed to move to the next page, meaning, has filled in all required fields. 

I generally don't like these kind of forms, because I sometimes just want to see what information I need to have to complete the form, before actually starting to fill it in, especially when the form is long!  But, we do have the left sidebar for navigation. I wonder if people would still realize that this can be used for navigation, especially when it goes out of the view after scrolling to the bottom. 

> What about Previous button?

Yeah, that could be useful to have.

**Comment by iperdomo** [comment]
> I wonder if people would still realize that this can be used for navigation, especially when it goes out of the view after scrolling to the bottom.

For me is not *evident* that the left navigation can be used for moving around the form. 

I'll merge the change and wait for feedback

**Review by iperdomo — APPROVED** [review]

**Comment by punchagan** [comment]
> I'll merge the change and wait for feedback

Fair enough. Thanks for merging.

**Pull request merged**
