### PR TITLE
Feature/redesign/resource view

### PR DESCRIPTION
**Pull request by navins94**

### CODE REVIEW

**Comment by martinchristov** [comment]
Should I wait for you to push an update according to what we spoke before reviewing?
https://www.figma.com/file/d4ZafjuA5MTMjy1Q8eitjo/Plastic-Strategies?type=design&node-id=33%3A7512&mode=design&t=XkRvtjEKIMB6lRWi-1

**Comment by navins94** [comment]
> Should I wait for you to push an update according to what we spoke before reviewing? https://www.figma.com/file/d4ZafjuA5MTMjy1Q8eitjo/Plastic-Strategies?type=design&node-id=33%3A7512&mode=design&t=XkRvtjEKIMB6lRWi-1

Yeah, it will be ready in 30 min

**Comment by navins94** [comment]
@martinchristov  Ready for review

**Comment by martinchristov** [comment]
@navins94 I pushed some fixes. Pls merge the branch. Thanks

**Pull request merged**
