### PR TITLE
[#367] Implement sign-up user flow

### PR DESCRIPTION
**Pull request by tangrammer**
force user to create auth0 account (email+password) after choosing which type of sign-up is going to chose

### CODE REVIEW

**Comment by wayangalihpratama** [comment]
I try to fill the form on `/stakeholder-signup` route and submit, 
I have this error message from network 
```
{
  "representation": [
    "missing required key"
  ]
}
```

**Comment by wayangalihpratama** [comment]
> force user to create auth0 account (email+password) after choosing which type of sign-up is going to chose

This is working fine

**Comment by tangrammer** [comment]
> I try to fill the form on `/stakeholder-signup` route and submit,
> I have this error message from network
> 
> ```
> {
>   "representation": [
>     "missing required key"
>   ]
> }
> ```
@wayangalihpratama 
 This PR only adds changes on the sign-up user flow not the backend apis, this is still a WIP ... I'm actually finishing now the fields/steps that each form should have

**Comment by wayangalihpratama** [comment]
> > I try to fill the form on `/stakeholder-signup` route and submit,
> > I have this error message from network
> > ```
> > {
> >   "representation": [
> >     "missing required key"
> >   ]
> > }
> > ```
> 
> @wayangalihpratama
> This PR only adds changes on the sign-up user flow not the backend apis, this is still a WIP ... I'm actually finishing now the fields/steps that each form should have

Ah ok @tangrammer, sorry for the misunderstanding
Then, I think the sign-up user flow was fine.

**Comment by tangrammer** [comment]
thanks for the review! @wayangalihpratama

**Pull request merged**
