### PR TITLE
[#612] Create case studies page

### PR DESCRIPTION
**Pull request by ifirmawan**
[#610] Make whole box clickable

[#612] Fix case studies n create left sidebar

### CODE REVIEW

**Review by navins94 — APPROVED** [review]

**Comment by loicsans** [comment]
@ifirmawan 
Right now this is how it looks, loads of details are missing:
Screenshot 2022-01-06 at 15 15 00
- [ ] the left navigation sidebar is way too wide
- [ ] The icon on the sidebar look inconsistent, the highlight marker is incomplete
Screenshot 2022-01-06 at 15 30 33
- [ ] We are missing the card top bar, where you should be able to switch from case studies with a dropdown, the learn more button should live there too along with a download button for each case study card.
Screenshot 2022-01-06 at 15 32 24
- [ ] Missing a white border (1px) above that card top nav
- [ ] We are missing a subtle frame container aroudn each cards, see below, it reinforces the card feel:

Screenshot 2022-01-06 at 15 34 50

- [ ] the image and the info neext to it on the right are separated by a 1px border rthe same color as the frame around the card.
- [ ] The location icon is huge on wide resolution
- [ ] The cards' title has to be bigger and bolder.

**Comment by ifirmawan** [comment]
Thanks for the review @loicsans, I'm trying to fix it

**Comment by loicsans** [comment]
@ifirmawan it looks much better, can you remove the added outline on the download button, use the same blue on :hover to color the actual text:
Screenshot 2022-01-11 at 9 55 36

**Comment by ifirmawan** [comment]
> @ifirmawan it looks much better, can you remove the added outline on the download button, use the same blue on :hover to color the actual text:
> Screenshot 2022-01-11 at 9 55 36

Sure thing @loicsans , I'm trying to fix it

**Comment by ifirmawan** [comment]
Hi @loicsans , I've fixed the added border on download button. You can continue to review it. Thanks

**Pull request merged**
